#!/bin/sh

dir=/var/www/taiga
back=$dir/taiga-back
env=$dir/env
pip=$env/bin/pip
python=$env/bin/python

sudo -u postgres createuser --superuser $USER
sudo -u postgres createdb taiga

cd $back && $python manage.py migrate --noinput
cd $back && $python manage.py loaddata initial_user
cd $back && $python manage.py loaddata initial_project_templates
cd $back && $python manage.py loaddata initial_role
cd $back && $python manage.py sample_data

pip2 install circus
service circus restart

rm -rf /etc/nginx/sites-enabled/default
service nginx restart
