#!/bin/sh

dir=/var/www/taiga
back=$dir/taiga-back
env=$dir/env
pip=$env/bin/pip
python=$env/bin/python

sudo -u postgres createuser --superuser taiga
sudo -u postgres createdb taiga

virtualenv -p /usr/bin/python3.4 $env
$pip install -r $back/requirements.txt
cd $back && $python manage.py migrate --noinput
cd $back && $python manage.py compilemessages
cd $back && $python manage.py collectstatic --noinput
cd $back && $python manage.py loaddata initial_user
cd $back && $python manage.py loaddata initial_project_templates
cd $back && $python manage.py loaddata initial_role
cd $back && $python manage.py sample_data
